/*
	Not Completed = 0
	Completed = 1
	In Progress = 2
	N/A = 3
*/

$launch_checklist_array = array(
		'Check for placeholder text content',
		'Check for gramatical errors & typos',
		'Check for placeholder images',
		'Check for excessive image file sizes',
		'Check for broken links',
		'Check that links go to intended page(s)',
		'Create a custom 404 error page',
		'store an exact copy of the current website',
		'Create redirects as needed',
		'Add a Favicon',
		'Test all forms for submission emails to client',
		'Ensure all forms have autoresponder emails',
		'Ensure all forms redirect to thank-you page upon submission',
		'Ensure every page has a meta title and meta description',
		'Create a sitemap & ensure accuracy',
		'submit the sitemap to Google Search Console',
		'ensure all opengraph/social media elements are specified',
		'ensure all opengraph/social media elements are specified',
		'verify social media icons & links are correct',
		'create a privacy policy page and link in footer',
		'create a terms & conditions page and link in footer',
		'create & store a backup of current DNS zone files',
		'search database for development links & replace',
		'ensure all images have appropriate ALT tags',
		'connect google analytics',
		'clean up post & blog categories',
		'Implement reCaptcha on all forms',
		'activate spam reduction solution',
		'delete all development & temporary plugins',
		'delete all development & temporary pages',
		'delete all development & temporary posts',
		'delete all development & temporary user accounts',
		'change all user account passwords',
		'ensure the \'Discourage Search Engines\' box is unchecked',
		'create & configure robots.txt file as needed',
		'ensure phone numbers in header and footer are correct and linked',
		'ensure email addresses in header and footer are correct and linked',
		'Double-check headinng hierarchy on every page',
		'Ensure commennts are disabled',
		'Ensure mobile menu functionality',
		'Ensure general mobile functionality',
		'Set Timezone settings',
		'Ensure full SSL/HTTPS security on every page',
		'Implement limited login functionality and test',
		'Ensure automatic plugin updates are turned on',
		'Delete the wp-config-sample.php file',
		'Whitelist Level Up IP Addresses',
		'Change the default Login Page URL',
		'Disable File Editing - wp-config.php - define(\'DISALLOW_FILE_EDIT\', true);',
		'Change the default WordPress Database Prefix',
		'Automatically Log Out Idle Users',
		'Hide the WordPress Version',
	);